-- EMPRESA O EAPB POR USUARIOS 

SELECT DISTINCT
GENPACIEN.PACNUMDOC AS A_4_Número,
GENDETCON.GDENOMBRE AS A_0_EAPB,
CASE WHEN GENDETCON.GDEPOSSUB = 1 THEN 'SUBSIDIADO' WHEN GENDETCON.GDEPOSSUB = 0 THEN 'CONTRIBUTIVO' ELSE '' END AS A_1_EAPB
--FORMAT(ADNINGRESO.AINFECING, 'yyyy-MM-dd', 'en-us') AS F_init
--GENDETCON.*
FROM ADNINGRESO
INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
INNER JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
-- filtros
WHERE ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2024-07-01', 120) AND CONVERT(DATETIME, '2024-09-01', 120)
