-- GRUPO ETNICO

SELECT DISTINCT
GENPACIEN.PACNUMDOC AS A_4_Número,
GENPACIEN.ADNGRUETN AS NUMERO_DB,
ADNGRUETN.ADGGRUETN AS A_11_ETNIA,

ADNGRUETN.ADGENOMBRE AS NOMBRE_ETNIA,
ADNGRUETN.*
FROM ADNINGRESO
INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
INNER JOIN ADNGRUETN ON GENPACIEN.ADNGRUETN = ADNGRUETN.ADGGRUETN

WHERE --ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2024-07-01', 120) AND CONVERT(DATETIME, '2024-08-02', 120)
--AND 
--GENPACIEN.PACNUMDOC = '1067530936'-- INDIGENA
GENPACIEN.PACNUMDOC = '1107060034'-- NINGUNA

select * from  ADNGRUETN;


-- OBSERVACIONES
-- tabla usada en db es https://web.sispro.gov.co/WebPublico/Consultas/ConsultarDetalleReferenciaBasica.aspx?Code=MDECEtnia
-- tabla en la resolucion https://web.sispro.gov.co/WebPublico/Consultas/ConsultarDetalleReferenciaBasica.aspx?Code=GrupoEtnico