
SELECT DISTINCT
GENPACIEN.PACNUMDOC AS A_4_Número,
    CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'M' WHEN GENPACIEN.GPASEXPAC = 2 THEN 'F' ELSE NULL END AS A_10_SEXO,
        DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) - CASE WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING) OR  (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING) AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING))) THEN 1 ELSE 0 END AS A_0_EDAD,
			FORMAT(HCNRESEXA.HCRFECRES, 'yyyy-MM-dd', 'en-us') AS F_Resultado,
            GENSERIPS.SIPCODCUP AS Información_Servicio,
            
			CASE 
			WHEN GENSERIPS.SIPCODCUP = '901101' THEN 'BACILOSCOPIA'
			WHEN GENSERIPS.SIPCODCUP = '907008' THEN 'SANGRE_OCULTAMF'
			WHEN GENSERIPS.SIPCODCUP = '906610' THEN 'ANTIGENO_PROSTATA'
			WHEN GENSERIPS.SIPCODCUP = '903895' THEN 'CREATININA' 
			WHEN GENSERIPS.SIPCODCUP = '906625' THEN 'GONADOTROPINA'
			WHEN GENSERIPS.SIPCODCUP = '904508' THEN 'GONADOTROPINA'
			WHEN GENSERIPS.SIPCODCUP = '903815' THEN 'COLESTEROL_HDL'
			WHEN GENSERIPS.SIPCODCUP = '902210' THEN 'HEMOGRAMA' 
			WHEN GENSERIPS.SIPCODCUP = '902213' THEN 'HEMOGRAMA'
			WHEN GENSERIPS.SIPCODCUP = '908806' THEN 'HEPATITIS_B'
			WHEN GENSERIPS.SIPCODCUP = '906223' THEN 'HEPATITIS_B'
			WHEN GENSERIPS.SIPCODCUP = '906317' THEN 'HEPATITIS_B'
			WHEN GENSERIPS.SIPCODCUP = '906225' THEN 'Hepatitis_C'
			WHEN GENSERIPS.SIPCODCUP = '908807' THEN 'Hepatitis_C'
			WHEN GENSERIPS.SIPCODCUP = '903816' THEN 'COLESTEROL_LDL'
			WHEN GENSERIPS.SIPCODCUP = '906039' THEN 'Treponema_pallidum'
			WHEN GENSERIPS.SIPCODCUP = '903868' THEN 'TRIGLICERIDOS' 
			WHEN GENSERIPS.SIPCODCUP = '906249' THEN 'Virus_Inmunodeficiencia'
			WHEN GENSERIPS.SIPCODCUP = '908832' THEN 'Virus_Inmunodeficiencia'
			WHEN GENSERIPS.SIPCODCUP = '18504' THEN 'COLONOSCOPIA'
			
			
			ELSE GENSERIPS.SIPCODCUP END AS tipo_exam,
			GENSERIPS.SIPDESCUP,

            HCNRESEXA.HCRDESCRIP AS Descripción
            FROM ADNINGRESO
            INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
            INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
			INNER JOIN HCNSOLEXA ON HCNFOLIO.OID = HCNSOLEXA.HCNFOLIO
			INNER JOIN HCNRESEXA ON HCNSOLEXA.OID = HCNRESEXA.HCNSOLEXA
            INNER JOIN GENSERIPS ON GENSERIPS.OID = HCNSOLEXA.GENSERIPS
            WHERE GENSERIPS.SIPCODCUP IN ('902210','903895','903868','906249','906039','906625','906317','906225','901101','903815','903815','907008','902213',
			'903816','904508','906610','908807','908806','908832','906223')
			and HCNRESEXA.HCRFECRES BETWEEN CONVERT(DATETIME, '2024-09-10', 120) AND CONVERT(DATETIME, '2024-09-12', 120)

			/*
SELECT DISTINCT
--HCNRESEXA.GENMEDICO,--NO MOSTRAR
--ADNINGRESO.AINCONSEC as ingreso,
--FORMAT(HCNSOLEXA.HCFECEST, 'dd/MM/yyyy hh:mm tt', 'en-us') AS Fecha_Solicitud,
--FORMAT(HCNRESEXA.HCRFECREA, 'dd/MM/yyyy hh:mm tt', 'en-us') AS F_Realización,

----FORMAT(HCNRESEXA.HCRFECRES, 'dd/MM/yyyy hh:mm tt', 'en-us') AS F_Resultado,

--GENPACIEN.GPANOMCOM AS Información_Paciente,
            --CASE WHEN GENPACIEN.GPATIPPAC = 2 THEN 'Subsidiado' ELSE NULL END AS Tipo_Paciente,
            --CASE WHEN GENPACIEN.GPASEXPAC = 1 THEN 'Masculino' WHEN GENPACIEN.GPASEXPAC = 2 THEN 'Femenino' ELSE NULL END AS sexo,
            --CASE GENPACIEN.PACTIPDOC WHEN 1 THEN 'Cédula_Ciudadanía' WHEN 2 THEN 'Cédula_Extrangeria' WHEN 3 THEN 'Tarjeta_Identidad' WHEN 4 THEN 'Registro_Civil' WHEN 5 THEN 'Pasaporte' WHEN 6 THEN 'Adulto_Sin_Identificacion' WHEN 7 THEN 'Menor_Sin_Identificacion' WHEN 8 THEN 'Numero_Unico' WHEN 10 THEN 'Nacido_vivo' WHEN 12 THEN 'Permiso_Especial' WHEN 14 THEN 'Permiso_Especial' WHEN 15 THEN 'Permiso_Especial' WHEN 9 THEN 'Permiso_Especial'
            --ELSE 'NONE' END AS Tipo_Documento,

            ----GENPACIEN.PACNUMDOC AS Número,

            --CONCAT(
            --    DATEDIFF(YEAR, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) - CASE WHEN (MONTH(GENPACIEN.GPAFECNAC) > MONTH(ADNINGRESO.AINFECING)  OR (MONTH(GENPACIEN.GPAFECNAC) = MONTH(ADNINGRESO.AINFECING)  AND DAY(GENPACIEN.GPAFECNAC) > DAY(ADNINGRESO.AINFECING)))  THEN 1  ELSE 0 END, ' Años / '--,
                ----(DATEDIFF(MONTH, GENPACIEN.GPAFECNAC, ADNINGRESO.AINFECING) - (CASE  WHEN DAY(ADNINGRESO.AINFECING) < DAY(GENPACIEN.GPAFECNAC)  THEN 1  ELSE 0  END)) % 12, ' Meses / '--,
                --DATEDIFF(DAY,  DATEADD(MONTH,  DATEDIFF(MONTH, 0, ADNINGRESO.AINFECING) -  (CASE  WHEN DAY(ADNINGRESO.AINFECING) < DAY(GENPACIEN.GPAFECNAC)  THEN 1  ELSE 0  END),  GENPACIEN.GPAFECNAC), ADNINGRESO.AINFECING), ' Días'
            --) AS edad_formateada,
            --CONVERT(VARCHAR, GENPACIEN.GPAFECNAC, 103) AS F_Nacimiento,
            --GENDETCON.GDECODIGO as E_P_S, GENDETCON.GDENOMBRE,
            --GENMEDICO.GMECODIGO,
            --GENMEDICO.GMENOMCOM as Médico,

            GENSERIPS.SIPCODCUP AS Información_Servicio,
            GENSERIPS.SIPDESCUP

            --HCNFOLIO.HCNUMFOL AS Folio,

            ----HCNRESEXA.HCRDESCRIP AS Descripción

            --HCNRESEXA.HCRANALIS AS Análisis,
            --HCNRESEXA.HCRDESCRIP AS Interpretacion,
            --GENMEDICO.GMENOMCOM as Profesional,
            --GENMEDICO.GMETARPRO AS Registro_Médico,
			-- falta nombre de especialidad
            --GENMEDICO.GMECODIGO,
			--GENARESER.GASNOMBRE
			--GENSERIPS.*
			--ADNINGRESO.*
            FROM ADNINGRESO
            INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
            INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
            --INNER JOIN GENDETCON ON GENPACIEN.GENDETCON = GENDETCON.OID
			INNER JOIN HCNSOLEXA ON HCNFOLIO.OID = HCNSOLEXA.HCNFOLIO
			INNER JOIN HCNRESEXA ON HCNSOLEXA.OID = HCNRESEXA.HCNSOLEXA
            INNER JOIN GENSERIPS ON GENSERIPS.OID = HCNSOLEXA.GENSERIPS
            --INNER JOIN GENMEDICO ON HCNRESEXA.GENMEDICO = GENMEDICO.OID
			--INNER JOIN GENARESER on HCNFOLIO.GENARESER =  GENARESER.OID
			
            WHERE GENSERIPS.SIPCODCUP IN ('18504','18514','901101','902210','902213','903815','903816','903868','903895','904508','906039','906220','906221','906222','906223','906225','906249','906250','906317','906318','906610','906625','907008','908806','908807','908832')
			AND HCNRESEXA.HCRFECRES BETWEEN CONVERT(DATETIME, '2024-08-01', 120) AND CONVERT(DATETIME, '2024-09-02', 120)


			*/