-- NIVEL EDUCATIVO

SELECT DISTINCT
GENPACIEN.PACNUMDOC AS A_4_Número,
GENPACIEN.GPANIVEDU AS A_13_NIVEL_EDUCATIVO
FROM ADNINGRESO
INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID

WHERE ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2024-07-01', 120) AND CONVERT(DATETIME, '2024-07-02', 120)