-- OCUPACION

SELECT DISTINCT
GENPACIEN.PACNUMDOC AS A_4_Número,
TRY_CAST(ADNINGRESO.ADINFPACI AS XML).value('(/HCCLInfoPaciente/@NOMOCUPA)[1]', 'VARCHAR(255)') AS NombreOcupacion,
TRY_CAST(ADNINGRESO.ADINFPACI AS XML).value('(/HCCLInfoPaciente/@CODOCUPA)[1]', 'VARCHAR(255)') AS COD
FROM ADNINGRESO
INNER JOIN HCNFOLIO ON HCNFOLIO.ADNINGRESO = ADNINGRESO.OID
INNER JOIN GENPACIEN ON HCNFOLIO.GENPACIEN = GENPACIEN.OID
WHERE ADNINGRESO.AINFECING BETWEEN CONVERT(DATETIME, '2024-08-01', 120) AND CONVERT(DATETIME, '2024-08-02', 120)
